language: c

sudo: false

env:
  global:
    - LUAROCKS=2.4.2
  matrix:
    - LUA=lua5.1

branches:
  only:
    - master
    - develop

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install busted

script:
  - busted